import type { NextPage } from 'next'
import Head from 'next/head'
// import Page from '../../'
import LocomotiveScroll from 'locomotive-scroll';
import { useEffect ,useRef} from 'react';
import HomePage from '../components/Home/HomePage';

const locomotiveScroll =
	typeof window !== `undefined` ? require('locomotive-scroll').default : null;


const Index: NextPage = () => {

const refScroll = useRef(null);


	useEffect(() => {
		if (!refScroll.current) return;
		// @ts-ignore
		let scroll: any;
		scroll = new locomotiveScroll({
			el: refScroll.current,
			smooth: true,
			smartphone: {
				smooth: true,
			},
			tablet: {
				smooth: true,
			},
			// inertia: 0.3,
			// multiplier: 0.65,
		});

  }, [refScroll]);
  
	return (
		<>
			<Head>
				<title>New Shoe</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<main data-scroll-container
				// ref={refScroll}
			>
				<HomePage />
			</main>
		</>
	);
};

export default Index
